### ISSUE TITLE
It takes ~3mn to compile with angular

### ISSUE THREAD

**Issue by ocombe** [6to5/6to5-brunch#5]
I have Angular 1.3.8 in my bower_components folder (`bower install angular`), and it bugs the 6to5-brunch compiler.
If I try the brunch debug option I can see that it halts at:
```sh
brunch:pipeline Compiling 'bower_components\angular\angular.js' with 'ES6to5Compiler' +1ms
```
There is no error, it just stops and the process takes ~30% of my processor until I kill it.

If I remove the 6to5-brunch module it works, if I remove the angular folder from bower_components it works fine as well.

edit: the compilation works, it just takes like 3mn to complete

**Comment by ocombe** [comment]
My bower file:

```js
{
  "name": "angular-brunch-seed-no-fuss",
  "version": "0.6.0",
  "dependencies": {
    "modernizr": "~2.8.3",
    "angular": "~1.3.8",
    "angular-resource": "~1.3.8",
    "angular-sanitize": "~1.3.8",
    "angular-mocks": "~1.3.8",
    "angular-ui-router": "0.2.13",
    "jquery": "~2.1.3",
    "lodash": "~2.4.1",
    "ocModal": "~0.1.9",
    "bootstrap-sass-official": "~3.3.1"
  },
  "overrides": {
    "angular-mocks": {
      "main": []
    },
    "modernizr": {
      "main": "modernizr.js"
    },
    "lodash": {
      "main": "dist/lodash.js"
    },
    "bootstrap-sass-official": {
      "main": [
		"assets/stylesheets/_bootstrap.scss",
		"assets/fonts/bootstrap/glyphicons-halflings-regular.eot",
		"assets/fonts/bootstrap/glyphicons-halflings-regular.svg",
		"assets/fonts/bootstrap/glyphicons-halflings-regular.ttf",
		"assets/fonts/bootstrap/glyphicons-halflings-regular.woff",
		"assets/javascripts/bootstrap.js"
		]
    }
  },
  "resolutions": {
    "angular": "~1.3.8"
  }
}

```

But If I just override angular it works (it takes 31s... but it works)

```js
{
  "name": "angular-brunch-seed-no-fuss",
  "version": "0.6.0",
  "dependencies": {
    "modernizr": "~2.8.3",
    "angular": "~1.3.8",
    "angular-resource": "~1.3.8",
    "angular-sanitize": "~1.3.8",
    "angular-mocks": "~1.3.8",
    "angular-ui-router": "0.2.13",
    "jquery": "~2.1.3",
    "lodash": "~2.4.1",
    "ocModal": "~0.1.9",
    "bootstrap-sass-official": "~3.3.1"
  },
  "overrides": {
    "angular": {
      "main": []
    },
    "angular-mocks": {
      "main": []
    },
    "modernizr": {
      "main": "modernizr.js"
    },
    "lodash": {
      "main": "dist/lodash.js"
    },
    "bootstrap-sass-official": {
      "main": [
		"assets/stylesheets/_bootstrap.scss",
		"assets/fonts/bootstrap/glyphicons-halflings-regular.eot",
		"assets/fonts/bootstrap/glyphicons-halflings-regular.svg",
		"assets/fonts/bootstrap/glyphicons-halflings-regular.ttf",
		"assets/fonts/bootstrap/glyphicons-halflings-regular.woff",
		"assets/javascripts/bootstrap.js"
		]
    }
  },
  "resolutions": {
    "angular": "~1.3.8"
  }
}
```

**Comment by ocombe** [comment]
If there was a way to ignore to bower_components (see https://github.com/6to5/6to5-brunch/issues/4) it would probably fix my problem, but it might be interesting to see why it takes so long to compile angular... Maybe it's just because the lib has a lot of code, but if that's the case then the 6to5 compiler is really inefficient!

**Comment by es128** [comment]
I realized sometime later after creating this plugin that even though it is theoretically harmless, 6to5 is not designed for processing code that was already targeting ES5 standards. 

#4 needs to be resolved to account for this (with a default value that excludes bower_components without requiring any user intervention).

If you think 6to5 ought to investigate why it is so slow to process angular.js (I don't), you could raise the topic in the core 6to5 issue tracker.

**Comment by ocombe** [comment]
I switched to Traceur for the moment, I'll take another look at 6to5 when #4 gets resolved. Anyway I think that Traceur is probably better for Angular code since Angular 2 uses Traceur.

**Comment by es128** [comment]
> Anyway I think that Traceur is probably better for Angular code since Angular 2 uses Traceur.

I would assert that the primary motivation there is that they're both Google products. 6to5 has many advantages over Traceur for any ES6 code (including angular apps) when evaluated objectively.

**Comment by ocombe** [comment]
Yes but 6to5 only includes validated specs and AtScript won't get validated for now. Traceur supports AtScript since they need it for Angular 2...

**Comment by es128** [comment]
Yeah if you're intending to use AtScript it's an entirely different story.

**Comment by ocombe** [comment]
Yes, I want my project to be Angular2-ready :)
